### ISSUE TITLE
Find art style

### ISSUE THREAD

**Issue by VectorWolf** [AgoutiGames/GameOff-2019-Plantower#1]
Here are some references for more cartoonish looking 3D environments, mainly forest ones.

![Pic1](https://i.ytimg.com/vi/12xx3YQgUXU/maxresdefault.jpg)
![Pic2](https://s3.amazonaws.com/gamegorillazmedia/productfiles/resized/cartoon_forest1.jpg)
![Pic3](https://assets.3dtotal.com/step-11.dt68tn.image.jhl.jpg)
![Pic4](https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/ad/Raptors_Image.png)
![Pic5](https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7e/Wolves_Image.png)

**Comment by ghost** [comment]
![trees_sketch](https://user-images.githubusercontent.com/37266387/68081793-c4bc0180-fe13-11e9-9b4e-4f1f58f04d72.png)
... I think the examples are very good. It helped me a lot. At first I wanted to get a color gradation through the pointiness of the objects. But that only works really well in Cycles. That's why I prefer Eevee - it also works faster. 

At first I dyed it rudimentarily, using different materials on vertexgroups. But I really like that. What do you mean?

**Comment by ghost** [comment]
With tree tops and a little darker on the trunk, filling the format and with a few happy friends... then it looks better.

![trees_sketch1](https://user-images.githubusercontent.com/37266387/68081925-fc2bad80-fe15-11e9-920c-3c15ecb14121.png)
